import classNames from "classnames";
import "./globals.css";
import { Roboto_Flex, Bai_Jamjuree } from "next/font/google";

const roboto = Roboto_Flex({ subsets: ["latin"], variable: "--font-roboto" });
const bayJamjuree = Bai_Jamjuree({
  subsets: ["latin"],
  weight: ["700"],
  variable: "--font-bai-jamjuree",
});

export const metadata = {
  title: "Space time",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={classNames(
          roboto.variable,
          bayJamjuree.variable,
          "bg-gray-900 font-sans text-gray-100"
        )}
      >
        {children}
      </body>
    </html>
  );
}
